<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>4481368e-498e-4d33-a927-0819aa73956d</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="ModelContextProtocol" Version="0.5.0-preview.1" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" Version="0.5.0-preview.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.11.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AiMultiAgent.Core\AiMultiAgent.Core.csproj" />
    <ProjectReference Include="..\AiMultiAgent.Mcp.Client\AiMultiAgent.Mcp.Client.csproj" />
  </ItemGroup>

</Project>
